moviefolder/web_app/urls.py
from . import views
from django.urls import path,include
app_name='web_app'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

moviefolder/web_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviefolder/web_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

moviefolder/web_app/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

moviefolder/web_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . forms import MovieForm
from . models import Movie


# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list': movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']

        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

moviefolder/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<div class="background">
  <div class="transbox">
        <form method="POST" enctype="multipart/form-data" class="form_style" style="border:2px solid;border-color:black;margin-left:38%;margin-top:5%;width:300px;padding-top:20px;padding-left:40px;height:380px;">
            {% csrf_token %}
            <input class="box" type="text" name="name" placeholder="Enter movie name"><br><br>
            <textarea class="des" type="text" name="desc" placeholder="Enter description" style="width:190px;height:100px;"></textarea><br><br>
            <input class="box" type="text" name="year" placeholder="Enter year"><br><br>
            <input class="box" type="file" name="img"><br><br>
            <input type="submit" class="sub" style="background-color:black;color:white;margin-left:100px;">
        </form>
  </div>
</div>
{% endblock %}

moviefolder/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
    <style>

    </style>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body class="outer" style="background-color:#cc0000;width:100%;">
<!-- Image and text -->
<nav class="navbar navbar-dark" style="background-color: #121111;height:80px;">
  <a class="navbar-brand" href="/">
      Online Movie Hub
  </a>
    <a class="btn btn-warning" href="{% url 'web_app:add_movie' %}" style="background-color:#e60000; font-weight:bold; color:white;">Add Movie</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

moviefolder/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <p style="font-size:24px;font-weight:bold;margin-left:38%;margin-top:20px;"> Are you sure to delete this movie?</p>
  <input type="submit" style="border-radius:4px;
text-align:center;
margin-left:650px;
font-size:20px;
background: #450104;
color: white;">
</form>
{% endblock %}

moviefolder/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" alt="" style="height:400px; width:500px; margin-top:40px;">
        </div>
        <div class="col-md-6" style="margin-top:20px;">
            <h2 style="color:white;">{{movie.name}}</h2>
            <p style="color:white;font-size:20px;text-align:justify;">{{movie.desc}}</p>
            <b style="color:white;">{{movie.year}}</b><br>
            <a style="margin-left:200px;font-weight:bold;" class="btn btn-warning" href="{% url 'web_app:update' movie.id %}">Update Movie</a>
            <a class="btn btn-danger" href="{% url 'web_app:delete' movie.id %}" style="margin-left:200px;font-weight:bold; background:black; font-size:1.1rem;color:yellow; margin-top:20px;">Delete Movie</a>
        </div>
    </div>
</div>


{% endblock %}

moviefolder/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data" style="margin-top:20px;margin-left:42%;color:white;padding-left:40px;padding-top:20px;padding-bottom:10px;border: 2px solid;width:350px;border-color:black;height:600x;">
    {% csrf_token %}
<h5 style="padding-left:10px;color:yellow;">Updating Details of Movie : {{movie.name}} </h5><br>
    <input class="box" type="text" name="name" placeholder="Enter movie name"><br><br>
            <textarea class="des" type="text" name="desc" placeholder="Enter description" style="width:190px;height:100px;"></textarea><br><br>
            <input class="box" type="text" name="year" placeholder="Enter year"><br><br>
            <input class="box" type="file" name="img"><br><br>
    <button type="submit" class="btn btn-warning" style="color:black;margin-left:60px;padding-top:5px;padding-left:10px;padding-bottom:5px;font-weight:bold;">Update</button>
</form>
{% endblock %}

moviefolder/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3" width="150px" height="300px" style="margin-top:20px; margin-left:50px; margin-right:20px;">
            <div class="card" style="width: 18rem; background:black;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="150px" height="200px" style="border:1px solid;border-color:grey;border-radius:2px;">
  <div class="card-body">
    <h5 class="card-title" style="color:white;">{{i.name}}</h5>
    <p class="card-text"></p>
    <a href="{% url 'web_app:detail' i.id %}" class="btn btn-primary" style="background:red; color: white;">More Info</a>
  </div>
</div>
        </div>
        <!--movie/{{i.id}}-->
    {% endfor %}
    </div>
</div>
<br>


{% endblock %}